### ISSUE TITLE
Missing Grafana Provisioning Folder & Dashboards

### ISSUE THREAD

**Issue by BrianChristie** [jaqx0r/blts#1]
Thanks for posting this, very helpful in figuring out how to do SLO & Error Budgets with real-world tools.

Here Grafana is started with `cfg:default.paths.provisioning=${GRAF}/prov` https://github.com/jaqx0r/blts/blob/master/grafana.sh#L8

It looks like the folder graf/prov/ which I think will contain the dashbaord definition JSON is possibly missing from the repo?

Grafana complains that it can't load the datasource

`EROR[12-14|13:25:42] can't read datasource provisioning files from directory logger=provisioning.datasources path=/Users/brian/GitHub/jaqx0r/blts/graf/prov/datasources`

**Comment by jaqx0r** [comment]
Well it's been a long time and I only just saw this report, and the bad news is I just tried to see the console and it's gone.  I assume an upgrade of grafana has happened and removed it -- I can't say for sure and I definitely regret not seeing this issue sooner!

I have to recreate the console from scratch now.

**Comment by jaqx0r** [comment]
I've committed something... I recreated the dashboard and I can see it's displaying something close to what I demoed in the past.  I am not 100% sure it's in the git repo tho.

**Comment by jaqx0r** [comment]
A partial solutino now exists. 

You have to run docker-compose to launch grafana, which currently means there's no data because I haven't hooked up the rest.

You need to follow the instructions from https://grafana.com/tutorials/provision-dashboards-and-data-sources/:

>In the sidebar, hover the cursor over Dashboards (squares) icon, and then click Manage. The dashboard appears in a Services folder.

and look for the SLO Burn Demo dashboard.

**Comment by jaqx0r** [comment]
OK now I've got a fully functioning console example with docker-copmose.  Hope this helps!

UNfortunately I can't figure out how to make the replace.sh work as per the README yet.
